const travelResponse="<div class=\"travel-answer\"><p>For Liberia Airport \u2192 Nosara, <strong>I\u2019d start with a shuttle.</strong> Here\u2019s how the options compare:</p><ul><li><strong>Private transfer \u2014 easiest:</strong> door-to-door in roughly 2.5\u20133 hours. Good for groups or a smooth arrival. <a href=\"https://daytrip.com/en/transfers/liberia-airport-cr/nosara-cr\" target=\"_blank\" rel=\"noopener\">See transfers</a></li><li><strong>Shared shuttle \u2014 an option for solo travelers:</strong> about $75 per person, with fixed departures and extra stops. Confirm the pickup point; it may be outside the terminal. <a href=\"https://buscostarica.rezdy.com/84858/liberia-to-nosara?lang=nb\" target=\"_blank\" rel=\"noopener\">See schedules</a></li><li><strong>Rental car \u2014 most flexible:</strong> useful for exploring. A 4x4/SUV is recommended for rough roads, especially in rainy season.</li><li><strong>Domestic flight \u2014 fastest:</strong> under an hour in the air, but pricier, with limited seats and tight luggage allowances.</li></ul><p><strong>My pick:</strong> compare a private transfer with a shared shuttle for your group size. Confirm current fares and pickup details before booking.</p><p>Want me to compare specific shuttle companies and pricing?</p></div>";
const existingCompareDemo=startCapabilityDemo;
startCapabilityDemo=function(){if(current!=='practice'){existingCompareDemo();return}runPersistentDemo([{request:'Hi Claude, what is the best way to get from the Liberia airport to Nosara beach in costa rica?',preservePrompt:true,statuses:['Thinking'],reply:'',output:()=>travelResponse,readDelay:10000},{request:'Can you map the specific shuttle companies with pricing into a word document I can print?',preservePrompt:true,statuses:['Generating a file...'],reply:'',output:()=>'<div class="travel-file-status">Ran 4 commands, read 3 files, and 2 more tools ›</div><p class="travel-answer">Here\'s the Word version, with clickable booking links and a formatted comparison table.</p><div class="travel-file"><span class="travel-file-icon"><i data-lucide="file"></i></span><span class="travel-file-name">Liberia to nosara transport<small>Document · DOCX</small></span><a href="liberia-to-nosara-transport.docx" download>Download <span>⌄</span></a></div>'}])};
const previousCompareTry=$('#tryBtn').onclick;$('#tryBtn').onclick=()=>{if(current==='practice')startCompareChat();else previousCompareTry()};
function startCompareChat(){resetMainWebsiteFlow();const area=$('#inlineConversation'),input=$('#composer');$('#home').classList.remove('hidden');$('#home').classList.add('has-conversation');$('#chatPreview').classList.add('hidden');area.classList.remove('hidden');area.replaceChildren();input.value='';input.readOnly=true;const prompt='Hi Claude, help me compare something';let n=0;const run=mainWebsiteRun;const later=(fn,ms)=>mainWebsiteTimers.push(setTimeout(()=>{if(mainWebsiteRun===run)fn()},ms));function type(){input.value=prompt.slice(0,++n);syncComposer();if(n<prompt.length){later(type,35);return}later(()=>{const user=document.createElement('div');user.className='demo-submitted-request';user.textContent=prompt;area.append(user);input.value='';syncComposer();const thinking=document.createElement('div');thinking.className='demo-assistant-row is-thinking';thinking.innerHTML=claudeMark+'<span>Thinking…</span>';area.append(thinking);later(async()=>{thinking.remove();const answer=document.createElement('p');answer.className='travel-answer';answer.textContent="I'd be glad to help! What would you like to compare?";area.append(answer);await streamResponseElement(answer);area.insertAdjacentHTML('beforeend','<div class="demo-response-footer">'+mainWebsiteFooterMarkup+'</div>');input.readOnly=false;input.placeholder='Write a message…';input.focus()},1400)},400)}type()}

function streamTravelResponse(markup,done){
 const transcript=$('#buildNarration'),viewport=$('.drawer-body');const source=document.createElement('div');source.innerHTML=markup;
 const answer=document.createElement('div');answer.className='travel-answer';transcript.append(answer);
 const blocks=[...source.firstElementChild.children];let index=0;
 function next(){if(!answer.isConnected)return;if(index===blocks.length){done();return}answer.append(blocks[index++].cloneNode(true));cancelAnimationFrame(demoPanFrame);viewport.scrollTo({top:viewport.scrollHeight,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'instant'});demoTimers.push(setTimeout(next,matchMedia('(prefers-reduced-motion: reduce)').matches?0:1100))}
 next();
}
