const plantCard=document.querySelector('[data-open-cap="plan"]');
plantCard.innerHTML='<div class="identity-art photo-art" aria-hidden="true"><div class="photo-print"><img src="plant.png" alt=""></div><i data-lucide="search"></i></div><div class="identity-copy"><h3>Make sense of a photo.</h3><p>Spot details. Know what to do next.</p></div><span class="card-arrow" aria-hidden="true">↗</span>';
capabilityFlows.plan.title='Make sense of a photo';examples.plan.cta='Try with your own photo';examples.plan.starter='';examples.plan.takeTitle='A fresh pair of eyes.';examples.plan.take='Show Claude a photo and ask what you’d like to understand.';
const priorDemo=startCapabilityDemo;
startCapabilityDemo=function(){if(current!=='plan'){priorDemo();return}runPersistentDemo([{request:'My plant is dying can I bring it back to life?',file:true,statuses:['Looking closely','Thinking'],reply:'',output:()=>"<div class=\"plant-answer\"><p>This looks like an indoor banana plant (Musa). <strong>The older leaves have yellow-and-brown damage, but the newer growth and shoots at the base are still green.</strong> That\u2019s an encouraging sign \u2014 it may be recoverable.</p><p><strong>Most likely causes:</strong> inconsistent watering or dry indoor air. Nutrient deficiency or crowded roots could also contribute.</p><p><strong>What I\u2019d do now</strong></p><ul><li><strong>Check the soil:</strong> water when the top 1\u20132 inches are dry, and let it drain fully. Don\u2019t leave it standing in water.</li><li><strong>Remove fully dead leaves:</strong> they won\u2019t recover. Keep leaves that still have healthy green tissue.</li><li><strong>Check its conditions:</strong> look for dry air and tightly circling roots if it hasn\u2019t been repotted in a while.</li></ul><p>Watch the new growth for improvement. Want help figuring out a watering schedule or talking through repotting?</p></div>"}])};
const picker=document.createElement('input');picker.type='file';picker.accept='image/*';picker.id='photoPicker';picker.hidden=true;document.body.append(picker);
let chosenPhoto=null,photoUrl=null;
const preview=document.createElement('div');preview.className='personal-photo-preview';preview.hidden=true;$('#composer').before(preview);
function clearPhoto(){chosenPhoto=null;if(photoUrl)URL.revokeObjectURL(photoUrl);photoUrl=null;preview.replaceChildren();preview.hidden=true;picker.value=''}
function pickPhoto(){picker.value='';picker.click()}
const priorTry=$('#tryBtn').onclick;$('#tryBtn').onclick=()=>{if(current==='plan')pickPhoto();else priorTry()};
picker.onchange=()=>{const file=picker.files[0];if(!file)return;if(!file.type.startsWith('image/')){showToast('Choose one image file.');return}clearPhoto();chosenPhoto=file;photoUrl=URL.createObjectURL(file);resetMainWebsiteFlow();$('#home').classList.remove('hidden');$('#chatPreview').classList.add('hidden');$('#inlineConversation').classList.add('hidden');preview.hidden=false;const img=document.createElement('img');img.src=photoUrl;img.alt='Your selected photo';const remove=document.createElement('button');remove.textContent='×';remove.setAttribute('aria-label','Remove attached photo');remove.onclick=clearPhoto;preview.append(img,remove);$('#composer').value='';$('#composer').placeholder='What would you like to know about this photo?';$('#composer').focus();syncComposer()};
const attach=document.createElement('button');attach.className='photo-attach';attach.type='button';attach.setAttribute('aria-label','Attach one photo');attach.innerHTML='<i data-lucide="paperclip"></i>';attach.onclick=pickPhoto;document.querySelector('#home .composer-bottom').prepend(attach);
const priorSend=send;send=function(){if(!chosenPhoto){priorSend();return}const prompt=$('#composer').value.trim();if(!prompt){$('#composer').focus();return}const area=$('#inlineConversation');area.replaceChildren();area.classList.remove('hidden');$('#home').classList.add('has-conversation');const user=document.createElement('div');user.className='demo-submitted-request plant-request';const image=document.createElement('img');image.src=photoUrl;image.alt='Your selected photo';const text=document.createElement('span');text.textContent=prompt;user.append(image,text);area.append(user);const note=document.createElement('p');note.className='plant-answer';note.textContent='Your photo and question are ready. In Claude, this would start your conversation. This prototype doesn’t upload or analyze your photo.';area.append(note);preview.hidden=true;chosenPhoto=null;$('#composer').value='';$('#composer').placeholder='Write a message…';syncComposer()};
const priorHome=home;home=function(){clearPhoto();priorHome()};$('#newChat').onclick=home;
lucide.createIcons();
const baseRender=render;render=function(){document.querySelector('#discoverDrawer').classList.toggle('photo-demo',current==='plan');baseRender()};
function revealPlantAnswer(markup){
 const transcript=$('#buildNarration'),viewport=$('.drawer-body');
 const source=document.createElement('div');source.innerHTML=markup;
 const answer=document.createElement('div');answer.className='plant-answer';transcript.append(answer);
 const parts=[];for(const node of source.firstElementChild.children){if(node.tagName==='UL'){const list=document.createElement('ul');parts.push(()=>answer.append(list));for(const item of node.children)parts.push(()=>list.append(item.cloneNode(true)))}else parts.push(()=>answer.append(node.cloneNode(true)))}
 let index=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 function reveal(){if(!answer.isConnected)return;if(index<parts.length){parts[index++]();const last=answer.lastElementChild;moveDemoTo(last);demoTimers.push(setTimeout(reveal,reduced?0:950));return}
 const footer=document.createElement('div');footer.className='response-end-mark';footer.innerHTML=claudeMark;transcript.append(footer);moveDemoTo(footer);$('#demoDraft').value='';$('#demoDraft').placeholder='Reply to Claude…';$('#demoDraftSend').onclick=null;
 }
 reveal();
}

Object.values(examples).forEach(example=>{if(example.starter)example.starter=greetDemoPrompt(example.starter);if(example.prompt)example.prompt=greetDemoPrompt(example.prompt)});
